name: sliding_sheet
description: A widget that can be dragged and scrolled in a single gesture and snapped to a list of extents.
version: 0.5.4
homepage: https://github.com/idabgsram/sliding_sheet
maintainer: Guzram

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: